apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: cache-ui
  name: cache-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/host: "true"
        io.kompose.service: cache-ui
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: rediscommander/redis-commander:latest
          name: redis-commander
          ports:
            - containerPort: 8081
          resources: {}
      hostname: redis-commander
      restartPolicy: Always
status: {}
