apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.network/host: "true"
        io.kompose.service: api
    spec:
      containers:
        - args:
            - tail
            - -f
            - /dev/null
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: env
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: env
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: env
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: AWS_SESSION_TOKEN
                  name: env
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_APPLICATION_CREDENTIALS
                  name: env
            - name: GOOGLE_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_APPLICATION_NAME
                  name: env
            - name: GO_ENV
              valueFrom:
                configMapKeyRef:
                  key: GO_ENV
                  name: env
            - name: MAILGUN_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: MAILGUN_API_KEY
                  name: env
            - name: ONESIGNAL_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: ONESIGNAL_API_KEY
                  name: env
            - name: SENDGRID_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: SENDGRID_API_KEY
                  name: env
            - name: TELEGRAM_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: TELEGRAM_API_KEY
                  name: env
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                configMapKeyRef:
                  key: TWILIO_ACCOUNT_SID
                  name: env
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: TWILIO_AUTH_TOKEN
                  name: env
          image: api
          name: api
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
